### ISSUE TITLE
yarn global add caz error

### ISSUE THREAD

**Issue by hsk863hh** [zce/caz-prev#142]
error fetch-blob@1.0.7: The engine "node" is incompatible with this module. Expected version "^10.17.0". Got "14.7.0
error Found incompatible module.

一定要把node 版本降到10.17吗

**Comment by zce** [comment]
这是 yarn 的一个问题，你可以改用 `$ npm i caz -g`，或者使用 `npx` 直接执行。

### 具体原因：

我在 caz 中使用了 beta 版本的 node-fetch，目前语义化依赖的版本是 `^3.0.0-beta.9`（截止目前最新的 beta 版本），恰巧 node-fetch 之前发布过一个 `3.0.0-beta.6-exportfix`（一个有问题的版本），而在 yarn 工具的理解里，`3.0.0-beta.6-exportfix` 版本大于 `3.0.0-beta.9`，所以 `^3.0.0-beta.9` 会自动安装 `3.0.0-beta.6-exportfix`，也就导致了你所看到的问题。

后面我也会尝试主动解决这个问题。

感谢你的报告～
